Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Loaded dependency [python3/3.9.6]: gcc/10.3.0-binutils-2.36.1
Loaded module: python3/3.9.6

Loading python3/3.9.6
  Loading requirement: gcc/10.3.0-binutils-2.36.1
Loaded dependency [numpy/1.21.1-python-3.9.6-openblas-0.3.17]: openblas/0.3.17
Loaded dependency [pandas/1.3.1-python-3.9.6]: numpy/1.21.1-python-3.9.6-openblas-0.3.17
Loaded module: pandas/1.3.1-python-3.9.6

Loading pandas/1.3.1-python-3.9.6
  Loading requirement: openblas/0.3.17 numpy/1.21.1-python-3.9.6-openblas-0.3.17
Loaded module: cuda/11.5
Loaded module: cudnn/v8.3.0.98-prod-cuda-11.5
Traceback (most recent call last):
  File "/zhome/45/c/128687/Github/Adv_ML/Scripts/../main.py", line 4, in <module>
    from src.models.laplace_model import laplace, laplace_eval, laplace_sample
  File "/zhome/45/c/128687/Github/Adv_ML/src/models/laplace_model.py", line 11, in <module>
    from src.data.dataloader import MURADataset
  File "/zhome/45/c/128687/Github/Adv_ML/src/data/dataloader.py", line 47, in <module>
    dataset = MURADataset(
  File "/zhome/45/c/128687/Github/Adv_ML/src/data/dataloader.py", line 9, in __init__
    anno_df = pd.read_csv(f"{data_dir}/{annotation_file}", names=["file", "label"])
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/MURA-v1.1/train_labeled_studies.csv'
Traceback (most recent call last):
  File "/zhome/45/c/128687/Github/Adv_ML/Scripts/../main.py", line 4, in <module>
    from src.models.laplace_model import laplace, laplace_eval, laplace_sample
  File "/zhome/45/c/128687/Github/Adv_ML/src/models/laplace_model.py", line 11, in <module>
    from src.data.dataloader import MURADataset
  File "/zhome/45/c/128687/Github/Adv_ML/src/data/dataloader.py", line 47, in <module>
    dataset = MURADataset(
  File "/zhome/45/c/128687/Github/Adv_ML/src/data/dataloader.py", line 9, in __init__
    anno_df = pd.read_csv(f"{data_dir}/{annotation_file}", names=["file", "label"])
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/MURA-v1.1/train_labeled_studies.csv'
Traceback (most recent call last):
  File "/zhome/45/c/128687/Github/Adv_ML/Scripts/../main.py", line 4, in <module>
    from src.models.laplace_model import laplace, laplace_eval, laplace_sample
  File "/zhome/45/c/128687/Github/Adv_ML/src/models/laplace_model.py", line 11, in <module>
    from src.data.dataloader import MURADataset
  File "/zhome/45/c/128687/Github/Adv_ML/src/data/dataloader.py", line 47, in <module>
    dataset = MURADataset(
  File "/zhome/45/c/128687/Github/Adv_ML/src/data/dataloader.py", line 9, in __init__
    anno_df = pd.read_csv(f"{data_dir}/{annotation_file}", names=["file", "label"])
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/MURA-v1.1/train_labeled_studies.csv'
Traceback (most recent call last):
  File "/zhome/45/c/128687/Github/Adv_ML/Scripts/../main.py", line 4, in <module>
    from src.models.laplace_model import laplace, laplace_eval, laplace_sample
  File "/zhome/45/c/128687/Github/Adv_ML/src/models/laplace_model.py", line 11, in <module>
    from src.data.dataloader import MURADataset
  File "/zhome/45/c/128687/Github/Adv_ML/src/data/dataloader.py", line 47, in <module>
    dataset = MURADataset(
  File "/zhome/45/c/128687/Github/Adv_ML/src/data/dataloader.py", line 9, in __init__
    anno_df = pd.read_csv(f"{data_dir}/{annotation_file}", names=["file", "label"])
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/MURA-v1.1/train_labeled_studies.csv'
Traceback (most recent call last):
  File "/zhome/45/c/128687/Github/Adv_ML/Scripts/../main.py", line 4, in <module>
    from src.models.laplace_model import laplace, laplace_eval, laplace_sample
  File "/zhome/45/c/128687/Github/Adv_ML/src/models/laplace_model.py", line 11, in <module>
    from src.data.dataloader import MURADataset
  File "/zhome/45/c/128687/Github/Adv_ML/src/data/dataloader.py", line 47, in <module>
    dataset = MURADataset(
  File "/zhome/45/c/128687/Github/Adv_ML/src/data/dataloader.py", line 9, in __init__
    anno_df = pd.read_csv(f"{data_dir}/{annotation_file}", names=["file", "label"])
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/MURA-v1.1/train_labeled_studies.csv'
Traceback (most recent call last):
  File "/zhome/45/c/128687/Github/Adv_ML/Scripts/../main.py", line 4, in <module>
    from src.models.laplace_model import laplace, laplace_eval, laplace_sample
  File "/zhome/45/c/128687/Github/Adv_ML/src/models/laplace_model.py", line 11, in <module>
    from src.data.dataloader import MURADataset
  File "/zhome/45/c/128687/Github/Adv_ML/src/data/dataloader.py", line 47, in <module>
    dataset = MURADataset(
  File "/zhome/45/c/128687/Github/Adv_ML/src/data/dataloader.py", line 9, in __init__
    anno_df = pd.read_csv(f"{data_dir}/{annotation_file}", names=["file", "label"])
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/appl/pandas/1.3.1-numpy-1.21.1-python-3.9.6/lib/python3.9/site-packages/pandas-1.3.1-py3.9-linux-x86_64.egg/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/MURA-v1.1/train_labeled_studies.csv'
